# xnapify (https://github.com/xuanhoa88/xnapify/)
#
# This source code is licensed under the MIT license found in the
# LICENSE.txt file in the root directory of this source tree.

version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore'
