/**
 * xnapify (https://github.com/xuanhoa88/xnapify/)
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

/**
 * A lightweight custom Emoji extension that uses ProseMirror's textInputRules
 * to convert common text emoticons and shortcodes to native Unicode emojis on the fly.
 */
export const EMOJI_DICTIONARY = {
  // Basic Emoticons
  ':-)': '🙂',
  ':)': '🙂',
  ';-)': '😉',
  ';)': '😉',
  ':-D': '😃',
  ':D': '😃',
  ':-(': '🙁',
  ':(': '🙁',
  ':-p': '😛',
  ':-P': '😛',
  ':p': '😛',
  ':P': '😛',
  ':-o': '😮',
  ':-O': '😮',
  ':o': '😮',
  ':O': '😮',
  ':-|': '😐',
  ':|': '😐',
  '<3': '❤️',
  '</3': '💔',

  // Common Shortcodes
  ':smile:': '😄',
  ':laughing:': '😆',
  ':joy:': '😂',
  ':rofl:': '🤣',
  ':sunglasses:': '😎',
  ':heart_eyes:': '😍',
  ':thumbsup:': '👍',
  ':+1:': '👍',
  ':thumbsdown:': '👎',
  ':-1:': '👎',
  ':pray:': '🙏',
  ':clap:': '👏',
  ':fire:': '🔥',
  ':100:': '💯',
  ':sparkles:': '✨',
  ':star:': '⭐',
  ':check:': '✅',
  ':x:': '❌',
  ':warning:': '⚠️',
  ':rocket:': '🚀',
  ':eyes:': '👀',

  // Extend with the remaining from the original array to ensure
  // the visual picker retains the full grid, even if they don't have shortcodes here.
  // The dictionary keys for these can just be their name or the emoji itself
  // if no shortcode is needed, but for input rules we only match strings starting with : or ;
  '😁': '😁',
  '😅': '😅',
  '😇': '😇',
  '🥰': '🥰',
  '🤩': '🤩',
  '😘': '😘',
  '😗': '😗',
  '😚': '😚',
  '😙': '😙',
  '😋': '😋',
  '😜': '😜',
  '🤪': '🤪',
  '😝': '😝',
  '🤑': '🤑',
  '🤗': '🤗',
  '🤭': '🤭',
  '🤫': '🤫',
  '🤔': '🤔',
  '🤐': '🤐',
  '🤨': '🤨',
  '😑': '😑',
  '😶': '😶',
  '😏': '😏',
  '😒': '😒',
  '🙄': '🙄',
  '😬': '😬',
  '🤥': '🤥',
  '😌': '😌',
  '😔': '😔',
  '😪': '😪',
  '🤤': '🤤',
  '😴': '😴',
  '😷': '😷',
  '🤒': '🤒',
  '🤕': '🤕',
  '🤢': '🤢',
  '🤮': '🤮',
  '🤧': '🤧',
  '🥵': '🥵',
  '🥶': '🥶',
  '🥴': '🥴',
  '😵': '😵',
  '🤯': '🤯',
  '🤠': '🤠',
  '🥳': '🥳',
  '🤓': '🤓',
  '🧐': '🧐',
  '👌': '👌',
  '✌️': '✌️',
  '🤞': '🤞',
  '🤟': '🤟',
  '🤘': '🤘',
  '🤙': '🤙',
  '👈': '👈',
  '👉': '👉',
  '👆': '👆',
  '👇': '👇',
  '☝️': '☝️',
  '✋': '✋',
  '🤚': '🤚',
  '🖐️': '🖐️',
  '🖖': '🖖',
  '👋': '👋',
  '💪': '💪',
  '🦾': '🦾',
  '🖕': '🖕',
  '✍️': '✍️',
  '🩷': '🩷',
  '🧡': '🧡',
  '💛': '💛',
  '💚': '💚',
  '💙': '💙',
  '🩵': '🩵',
  '💜': '💜',
  '🖤': '🖤',
  '🩶': '🩶',
  '🤍': '🤍',
  '🤎': '🤎',
  '❤️‍🔥': '❤️‍🔥',
  '❤️‍🩹': '❤️‍🩹',
  '💕': '💕',
  '💞': '💞',
  '💓': '💓',
  '💗': '💗',
  '💖': '💖',
  '💘': '💘',
  '💝': '💝',
  '💟': '💟',
};

// Deduplicate the values to get a flat array for the picker grid
export const COMMON_EMOJIS = [...new Set(Object.values(EMOJI_DICTIONARY))];
