'use strict';

/**
 * xnapify (https://github.com/xuanhoa88/xnapify/)
 *
 * Webpack loader that wraps an entry module in a dynamic import(),
 * creating the async boundary required by Module Federation to
 * initialise shared modules before application code runs.
 *
 * How it works
 * ────────────
 * 1. Webpack picks this loader up for every entry module (applied by
 *    AsyncModuleFederationPlugin via NormalModule.getCompilationHooks).
 * 2. Instead of running the entry directly, the generated module
 *    executes an async IIFE that awaits a dynamic import of the real
 *    entry, giving the Module Federation runtime time to initialise the
 *    shared scope before any application code runs.
 * 3. ASYNC_BOUNDARY_QUERY is appended to the re-import path so the
 *    plugin can recognise and skip it, preventing infinite recursion
 *    without disabling babel-loader (which !! would do, breaking JSX).
 *
 * Why an async IIFE and not bare top-level await
 * ───────────────────────────────────────────────
 * Top-level await requires output.module: true or an .mjs extension.
 * Most projects target CommonJS-compatible output, so an async IIFE is
 * used — it works universally and makes the boundary explicit.
 *
 * Why webpackPreload and not webpackPrefetch
 * ──────────────────────────────────────────
 * `webpackPreload` emits <link rel="preload"> so the browser fetches the
 * MF bootstrap chunk in parallel with the current page load. This is
 * correct because the chunk is needed immediately on first render.
 * `webpackPrefetch` defers fetching to idle time, risking a waterfall.
 *
 * CSS side-effect: MiniCssExtractPlugin attaches extracted CSS to this
 * async chunk rather than the synchronous entrypoint, so CSS will not
 * appear in entrypoints.client.assets in stats.json — only in
 * entrypoints.client.childAssets.preload and the flat assets list.
 * The StatsWriterPlugin accounts for this by sweeping statsData.assets
 * for all CSS files rather than relying on the entrypoint alone.
 *
 * Exports
 * ───────
 * Entry modules rarely export values. If yours does, this boundary will
 * silently drop them — restructure so the entry has no exports.
 */

module.exports = function asyncEntryLoader() {
  // Normalise path separators (Windows → POSIX) and strip any query string
  // webpack may have appended, otherwise the import() path is malformed.
  const resourcePath = this.resourcePath.replace(/\\/g, '/').split('?')[0];

  return [
    '// Module Federation async boundary — generated by AsyncModuleFederationPlugin.',
    '// Do not edit: this file is auto-generated at build time.',
    '',
    ';(async () => {',
    // JSON.stringify ensures the path is correctly escaped (quotes, backslashes,
    // unicode) regardless of OS or project directory naming.
    `  await import(/* webpackPreload: true */ ${JSON.stringify(resourcePath + '?async-boundary')});`,
    '})();',
  ].join('\n');
};

// Explicitly mark as a normal (non-raw) loader so webpack passes a string,
// not a Buffer, even when the resource happens to be binary.
module.exports.raw = false;
